### ISSUE TITLE
Script keeps returning a TypeError when run

### ISSUE THREAD

**Issue by Fironet** [tylerneylon/imghist#1]
After installing pycairo, pypng, and running the script using `imghist.py test.png output.png` (all in the one directory) I get the following error:

```
C:\Users\Fironet\Desktop\Color histograms>imghist.py test.png output
.png
Reading in image data.
Traceback (most recent call last):
  File "C:\Users\Fironet\Desktop\Color histograms\imghist.py", line
325, in <module>
    readImage()
  File "C:\Users\Fironet\Desktop\Color histograms\imghist.py", line
242, in readImage
    (h, l, s) = colorsys.rgb_to_hls(*tuple(row[i:i+3]))
TypeError: rgb_to_hls() takes exactly 3 arguments (1 given)
```

Is this an issue on my side? The image I'm wanting to process is 5000px wide, not sure if that is causing a problem. Any clarification would be great as I've been very much wanting to test this script.

**Comment by tylerneylon** [comment]
Thanks for the report. I'll take a careful look at this tomorrow and hopefully have a fix for you!

**Comment by Fironet** [comment]
Think I discovered what was causing the error. I was inputting an image with alpha transparency, and even when saved with a solid background the metadata was the same ('RGB with Alpha').

I then saved via an alternate method without the alpha metadata and this time it possibly ran out of memory:

```
C:\Users\Fironet\Desktop\Color histograms>imghist.py Test-white2.png
 output.png
Reading in image data.
Traceback (most recent call last):
  File "C:\Users\Fironet\Desktop\Color histograms\imghist.py", line
325, in <module>
    readImage()
  File "C:\Users\Fironet\Desktop\Color histograms\imghist.py", line
240, in readImage
    pixPts.append(row[i:i+3])
MemoryError
```

So I resized it to 50% instead and it worked. Will test it a bit more, and thanks for the work on it, was looking for such a color analyzer. A very nice one can also be found for Matlab [here](http://www.mathworks.com/matlabcentral/fileexchange/20757-drawing-color-histograms-and-color-clouds), but I've yet to try it.

**Comment by tylerneylon** [comment]
Ok. I'm interested in making imghist work on images with an alpha channel. If I have some time, I'll try to fix that.

Thanks for the matlab link - that looks cool.

If you don't mind, could you send over a sample image with alpha that reproduces the original error?

**Comment by Fironet** [comment]
> If you don't mind, could you send over a sample image with alpha that reproduces the original error?

Sure, [here's one](http://i.imgur.com/bRhxgbL.png) I put together, using the same metadata. Also on [another PNG](http://i.imgur.com/YlzlfBF.png) tested the same error returns but with `3 arguments (2 given)` rather than `(1 given)`.

One thing I wanted to know as well, I tried the output size option of the script and it works perfectly, but is there a also way to produce more than 5 pie slices in the output?

**Comment by tylerneylon** [comment]
Great! Thank you! :+1:

**Comment by Fironet** [comment]
Thanks for the fix! Wish I also knew how to add more color slices to the pie output, although I did try adjusting the various global values.

**Comment by tylerneylon** [comment]
Sure thing. I added issue #2 to add the parameter you're looking for. I don't know when I'll get to that, though.
